# Generated by Django 3.0.6 on 2020-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infopubldate', models.DateField(verbose_name='新闻发布日期')),
                ('infopubltime', models.CharField(max_length=8, null=True, verbose_name='新闻发布时间')),
                ('media', models.CharField(max_length=50, null=True, verbose_name='媒体出处')),
                ('newscategory', models.CharField(max_length=200, null=True, verbose_name='新闻栏目')),
                ('infotitle', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('infoshorttitle', models.CharField(max_length=200, null=True, verbose_name='新闻副标题')),
                ('abstract', models.TextField(null=True, verbose_name='新闻摘要')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('author', models.CharField(max_length=200, null=True, verbose_name='撰写作者')),
                ('linkaddress', models.CharField(max_length=300, null=True, verbose_name='链接地址')),
                ('category', models.CharField(max_length=50, verbose_name='栏目分类')),
                ('infolevel', models.IntegerField(verbose_name='信息级别')),
            ],
            options={
                'verbose_name': '新闻资讯表',
                'verbose_name_plural': '新闻资讯表',
                'db_table': 'news_newsinfo',
            },
        ),
    ]
